### PR TITLE
adds tenantId as a header to websocket connection

### PR DESCRIPTION
**Pull request by troyibm**

### CODE REVIEW

**Review by esilky — APPROVED** [review]
Looks good.
One of the changes is 'whitespace', I'm looking at ways to standardize a format.

**Comment by troyibm** [comment]
it has conflicts, so I will merge those in
But thanks for the look through @esilky !

**Comment by esilky** [comment]
It seems like the conflict is that we changed 'IAMAPIKey' to 'iamApiKey' (to conform to Java standards). That should be easy to resolve.

**Comment by troyibm** [comment]
Actually @esilky, you changed it to `iamAPiKey`.  The middle P is still capital.  But don't fix that until after merge this PR.  And if you want to do the honors, that's fine with me.

**Comment by arivatibm** [comment]
@esilky @troyibm please do not merge this code until:
1. I approve it from an architectural and security perspective (I have a meeting with Jaydeep to discuss it)
2. Audio Gateway is refactored to support receiving a tenant ID 
3. QA testing is done

**Comment by esilky** [comment]
I fixed that in my Unit-Test PR.
I am in the process of getting that updated with master for review and merge.  So, it's fixed, but it shouldn't cause you problems.

**Comment by esilky** [comment]
@arivatibm I'll let you merge.  @erezbi The unit-test PR is updated to pull master into it to resolve the conflicts.  That also updates the name mentioned above.

**Comment by arivatibm** [comment]
I have created my own pull request for this fix that works also with the audio gateway

**Pull request closed without merging**
