### PR TITLE
Esilky  update kit #31

### PR DESCRIPTION
**Pull request by esilky**
Changes the socket ports used by default for Controller command and audio sockets to avoid a conflict when the client is used on a machine running a Node server on the default port.

Changes the status blink rate (people thought it was too slow). Changes the characters used to indicate status blink in the console to simply it.

Changes the GPIO pins used to avoid conflicts with a Sense-Hat display if installed in parallel.

### CODE REVIEW

**Comment by esilky** [comment]
Issues addressed:
Change GPIO pins used for simple interface to not conflict with Sense-HAT - https://github.com/Watson-Personal-Assistant/AudioClientSampleCodeJava/issues/13
Change default Controller Interface socket ports used - https://github.com/Watson-Personal-Assistant/AudioClientSampleCodeJava/issues/14
Speed up the status blink rate when playing the response - https://github.com/Watson-Personal-Assistant/AudioClientSampleCodeJava/issues/15

**Review by avolcoff — APPROVED** [review]

**Comment by avolcoff** [comment]
@esilky Please have QA test this change before merging

**Review by arivatibm — APPROVED** [review]

**Comment by esilky** [comment]
@rameshupadhyaper  Do you have the Andrea Kit? That is what we know is currently using the *Control Interface* and the *Sense HAT*.

Lacking that, you can probably only test the blink rate using the 'new' status characters on the console.  You should see a 1/2 second 'blink' on/off output to the console of '[+]' / '[-]'.
The other option is to build one of the 'Simple Interface' boards for the Raspberry Pi from the schematics in the README. If you do that you should see the Blue LED blink at the 1/2 second rate (1/2 on / 1/2 off).

**Comment by rameshupadhyaper** [comment]
we have  Andrea Kit  but I haven't  configured  it.

**Comment by esilky** [comment]
Are there specific issues that you are having following the instructions? 
I would like to know about them so I can improve the instructions.

-Ed

Ed Silky
Senior Technical Staff Member
IBM Watson IoT Platform

Phone: 1-925-277-5061 (office) 1-925-895-3266 (Mobile) 
E-mail: esilky@us.ibm.com 
4000 Executive Pkwy 
Suite 300 
San Ramon, CA 94583 
United States

**Pull request merged**
