### PR TITLE
Esilky  perflogging #415

### PR DESCRIPTION
**Pull request by esilky**
Added performance logging by configuring log4j2.xml.  See the README.md for information about the logging.

### CODE REVIEW

**Review by arivatibm — APPROVED** [review]

**Comment by arivatibm** [comment]
@esilky please have one of the QAs test this change before we merge to master

**Comment by esilky** [comment]
@rameshupadhyaper  can you please run through tests of this.
1) With the log4j2.xml perf category configured to `debug` verify that a perf log is created and has entries when questions are asked.
2) With the log4j2.xml perf category configured to `info` verify that entries are not added.

Refer to the README.md

**Comment by esilky** [comment]
@rameshupadhyaper when do you think it will be possible to do this testing?  I'd like to get this change merged before doing more work if possible.

**Comment by rameshupadhyaper** [comment]
@esilky  After running AudioClientSampleCodeJava with log4j2.xml perf category configured to debug ,blank perf.log file has been created but console logs get updated with logs . Please provide your input to create file with entries. 
Readme doesn't not have much info.

**Comment by rameshupadhyaper** [comment]
Please find console log after running.
2018-07-27 13:55:23,365 pool-1-thread-1 DEBUG Stopping LoggerContext[name=6d6f6e28, org.apache.logging.log4j.core.LoggerContext@5a56cdac]
2018-07-27 13:55:23,366 pool-1-thread-1 DEBUG Stopping LoggerContext[name=6d6f6e28, org.apache.logging.log4j.core.LoggerContext@5a56cdac]...
2018-07-27 13:55:23,371 pool-1-thread-1 DEBUG Shutting down RollingFileManager logs/perf.log
2018-07-27 13:55:23,372 pool-1-thread-1 DEBUG Shutting down RollingFileManager {}logs/perf.log
2018-07-27 13:55:23,374 pool-1-thread-1 DEBUG All asynchronous threads have terminated
2018-07-27 13:55:23,374 pool-1-thread-1 DEBUG RollingFileManager shutdown completed with status true
2018-07-27 13:55:23,375 pool-1-thread-1 DEBUG Shut down RollingFileManager logs/perf.log, all resources released: true
2018-07-27 13:55:23,375 pool-1-thread-1 DEBUG Appender PERFORMANCE stopped with status true
2018-07-27 13:55:23,376 pool-1-thread-1 DEBUG Shutting down RollingFileManager logs/client.log
2018-07-27 13:55:23,376 pool-1-thread-1 DEBUG Shutting down RollingFileManager {}logs/client.log
2018-07-27 13:55:23,378 pool-1-thread-1 DEBUG All asynchronous threads have terminated
2018-07-27 13:55:23,379 pool-1-thread-1 DEBUG RollingFileManager shutdown completed with status true
2018-07-27 13:55:23,379 pool-1-thread-1 DEBUG Shut down RollingFileManager logs/client.log, all resources released: true
2018-07-27 13:55:23,380 pool-1-thread-1 DEBUG Appender LOG-FILE stopped with status true
2018-07-27 13:55:23,381 pool-1-thread-1 DEBUG Shutting down OutputStreamManager SYSTEM_OUT.false.false
2018-07-27 13:55:23,381 pool-1-thread-1 DEBUG Shut down OutputStreamManager SYSTEM_OUT.false.false, all resources released: true
2018-07-27 13:55:23,381 pool-1-thread-1 DEBUG Appender Console stopped with status true
2018-07-27 13:55:23,382 pool-1-thread-1 DEBUG Log4j2 ConfigurationScheduler shutting down threads in java.util.concurrent.ScheduledThreadPoolExecutor@5a17e31e[Running, pool size = 1, active threads = 0, queued tasks = 1, completed tasks = 0]
2018-07-27 13:55:23,383 pool-1-thread-1 DEBUG Stopped XmlConfiguration[location=D:\Hotel solution code\With Venue changes\Ramesh\AudioClientSampleCodeJava\.\config\log4j2.xml] OK
2018-07-27 13:55:23,383 pool-1-thread-1 DEBUG Stopped LoggerContext[name=6d6f6e28, org.apache.logging.log4j.core.LoggerContext@5a56cdac] with status true

**Comment by rameshupadhyaper** [comment]
@esilky I will be travelling today. You may contact @sbhorjar he will do testing.
email id:sbhorjar@in.ibm.com

**Comment by esilky** [comment]
@rameshupadhyaper @sbhorjar I haven't seen that error and can't reproduce it.  Maybe we should set up a meeting to view it together.

**Comment by esilky** [comment]
@rameshupadhyaper @sbhorjar any update?  We would like to get this merged.

**Comment by esilky** [comment]
@rameshupadhyaper @sbhorjar any update? We would like to get this merged.

**Comment by Sourabhorjare** [comment]
@esilky You can merge this and please share the steps to run and get perf logs in brief.

**Pull request merged**
